### PR TITLE
doc(config): add mailgun to the example config file

### PR DESCRIPTION
**Pull request by RomainLanz**

### CODE REVIEW

**Comment by RomainLanz** [comment]
Aaaah, hate those tests haha

**Comment by thetutlage** [comment]
Travis has gone made, there is a failed test and it says build passed. 
screen shot 2016-08-19 at 1 16 25 pm

**Comment by thetutlage** [comment]
Travis is driving me nuts.. Let me see what the heck the issue is, or may be I will move to Codeship

**Comment by RomainLanz** [comment]
@thetutlage Any news on this?

**Pull request closed without merging**
