### PR TITLE
Add SendGrid driver

### PR DESCRIPTION
**Pull request by nrempel**
This pull request adds a driver for [SendGrid](http://sendgrid.com).

It uses https://github.com/sendgrid/nodemailer-sendgrid-transport to handle sending mail.

To test it, create a free sendgrid account and run:

```
SENDGRID_APIKEY=<api key> npm test
```

### CODE REVIEW

**Comment by nrempel** [comment]
You can check the mail that was sent here: https://www.guerrillamail.com/inbox

Set the inbox to adonis-sg@sharklasers.com

**Comment by nrempel** [comment]
Hmm, not sure why coverage has decreased on some files. I've only added a new file and accompanying test.

**Comment by nrempel** [comment]
It looks like the full suite of tests is not running correctly. It seems to get cut off here https://travis-ci.org/adonisjs/adonis-mail/jobs/139555224#L658

**Comment by thetutlage** [comment]
There is a disclaimer saying `sendgrid` will not support the node-mailer transport post June 1st. So it does not make sense to use a deprecated library.

**Comment by nrempel** [comment]
Good point, I've updated the code to use the API directly.

**Comment by nrempel** [comment]
@thetutlage why did you close this? I'm happy to make any changes you request.

**Comment by thetutlage** [comment]
Ooops sorry, I thought the PR is from greenkeeper. Let me go through the PR once again

**Comment by nrempel** [comment]
Ok thanks!

**Comment by SAGV** [comment]
@thetutlage This still seems pretty useful…

**Comment by thetutlage** [comment]
Closing and will write SendGrid driver from scratch, quite a few things have changed and this library needs some cleanup, also with removing Mandrill driver

**Comment by zooshme** [comment]
Any news on a driver for SendGrid?

**Comment by kush-prof** [comment]
@thetutlage Are you planning to write the SendGrid driver soon for AdonisJs Mail, I can help with it if you are not planning in recent future?

**Comment by emmsdan** [comment]
@thetutlage I am hoping we will get to see Sendgrid in v6

**Pull request closed without merging**
