### PR TITLE
feat(*): rewrite for 4.0

### PR DESCRIPTION
**Pull request by ntvsx193**
Good evening!
I rewrite for support adonis v 4.0.
I check changes on app with smtp.

Unit & functional tests not rewrite. I don't know your ideology.
Thx!

### CODE REVIEW

**Comment by ntvsx193** [comment]
Second part of code :)
I restore tests

**Comment by ntvsx193** [comment]
I don't know nothing about drivers auth keys (i.e. MAILGUN_APIKEY and etc...) and this tests is crashed.

**Comment by thetutlage** [comment]
@ntvsx193 I pulled the changes and there seems to be some good amount of fixes required. Also `node-mailer 4.0` API has been changed a bit.

I will upgrade this package myself soon

**Comment by ntvsx193** [comment]
I use node-mailer 4.0 and it's worked.

**Comment by thetutlage** [comment]
I have got another branch `dawn` up and running with a single driver `smtp`. Feel free to contribute there if you want.

**Comment by thetutlage** [comment]
Also old tests are flaky, so I don't want to maintain them anymore, it's better to clean up from scratch

**Pull request closed without merging**
